### ISSUE TITLE
3 tests kicked off in parallel instead of one

### ISSUE THREAD

**Issue by tamifist** [bitrise-io/steps-xamarin-test-cloud-for-android#19]
I've added "Xamarin Test Cloud for Android" step and set test_cloud_devices variable pointing to single device. However each time when I am running CI build I have 3 parallel test runs in cloud for the same device.

**Comment by godrei** [comment]
Hi @tamifist ,
the issue is fixed in version [2.0.0](https://github.com/bitrise-steplib/steps-xamarin-test-cloud-for-android/releases/tag/2.0.0), available in the steplib.
