### ISSUE TITLE
Build fails when iOS builds fail

### ISSUE THREAD

**Issue by jillburg7** [bitrise-io/steps-xamarin-test-cloud-for-android#23]
The Android Xamarin Test Cloud step build fails when a build target for the Xamarin.iOS project fails. The expected behavior is that Xamarin.Android should be able to build if it succeeds and run on Test Cloud regardless if iOS build fails. (This used to be the behavior in v2.1.0.) "Should this step run even if a previous step failed?" is marked as true for both this is step and the iOS Test Cloud step.

Snippet of Bitrise log:
```
Done building project "/Users/vagrant/git/Droid/Application.Droid.csproj".

Build succeeded.

Warnings:

/Users/vagrant/git/Droid/Application.Droid.csproj (PackageForAndroid) ->
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.Targets (CoreCompile target) ->

	MainActivity.cs(76,19): warning CS0618: `HockeyApp.Android.Metrics.MetricsManager.Register(Android.Content.Context, Android.App.Application, string)' is obsolete: `deprecated'

	 1 Warning(s)
	 0 Error(s)

Time Elapsed 00:01:05.2338940

Building test project: Application.UITests
$ "/Applications/Xamarin Studio.app/Contents/MacOS/mdtool" "build" "/Users/vagrant/git/Application.sln" "-c:Debug" "-p:Application.UITests"

Run in diagnostic mode
Xamarin Studio Build Tool
Loading solution: /Users/vagrant/git/Application.sln
   Loading projects ..
Building: Application.UITests (Debug)
   /Users/vagrant/git/iOS/Resources/Images.xcassets/Sample.imageset/Sample~iphone.pdf: error : File not found: /Users/vagrant/git/iOS/Resources/Images.xcassets/Sample.imageset/Sample~iphone.pdf
Build failed, error: exit status 1
```

**Comment by godrei** [comment]
Hi @jillburg7 ,
you can control which projects to build by solution - project, configuration - platform mapping in your xamarin solution.
If you want to avoid building the ios project, please add a solution config+platform to your solution, which only maps to your android project and use this solution config+platform in the Test Cloud step.

**Comment by godrei** [comment]
Closing as we did not receive a reply - @jillburg7 please let us know if we can help with anything and we'll reopen this issue!
